# Generated by Django 5.1.5 on 2025-02-04 03:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=254, unique=True, validators=[django.core.validators.EmailValidator(message='Enter a valid email address'), django.core.validators.RegexValidator(message='Enter a valid email address', regex='^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,}$')])),
                ('password', models.CharField(max_length=128)),
                ('photo', models.CharField()),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('student', 'Student'), ('employer', 'Employer')], default='student', max_length=20)),
            ],
        ),
    ]
