# Generated by Django 5.1.5 on 2025-02-05 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_employer_user_ptr_remove_user_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('candidate', 'Candidate'), ('employer', 'Employer')], default=None, max_length=20, null=True),
        ),
    ]
