# Generated by Django 5.1.5 on 2025-02-05 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidateprofile',
            name='skills',
            field=models.CharField(),
        ),
    ]
