# Generated by Django 5.1.5 on 2025-02-08 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_active_user_changepasswordat_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='changePasswordAt',
        ),
    ]
