# Generated by Django 5.1.5 on 2025-02-26 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_user_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateprofile',
            name='experience',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='interests',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
