# Generated by Django 5.1.5 on 2025-03-16 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_user_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='employerprofile',
            name='about_company',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employerprofile',
            name='company_size',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
