# Generated by Django 5.1.5 on 2025-02-18 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='resume',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
