# Generated by Django 5.1.5 on 2025-03-09 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_alter_application_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='contract',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='application',
            name='resume_text',
            field=models.CharField(blank=True, default=''),
        ),
    ]
