# Generated by Django 5.1.5 on 2025-03-09 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0004_application_contract_application_resume_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='contract',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
