# Generated by Django 5.1.5 on 2025-04-10 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0005_alter_application_contract'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='resume_text',
            new_name='extracted_resume',
        ),
    ]
