# Generated by Django 5.1.5 on 2025-02-10 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='joblisting',
            name='requirements',
        ),
        migrations.AddField(
            model_name='joblisting',
            name='job_type',
            field=models.CharField(choices=[('onsite', 'OnSite'), ('remote', 'Remote')], default='onsite', max_length=10),
        ),
    ]
