# Generated by Django 5.1.5 on 2025-02-18 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_remove_joblisting_requirements_joblisting_job_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='joblisting',
            name='job_location_type',
            field=models.CharField(choices=[('onsite', 'OnSite'), ('remote', 'Remote')], default='onsite', max_length=10),
        ),
        migrations.AddField(
            model_name='joblisting',
            name='job_status',
            field=models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], default='open', max_length=10),
        ),
        migrations.AlterField(
            model_name='joblisting',
            name='job_type',
            field=models.CharField(choices=[('internship', 'InternShip'), ('full time', 'Full Time'), ('part time', 'Part Time')], default='full time', max_length=10),
        ),
    ]
