# Generated by Django 5.1.5 on 2025-03-07 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_joblisting_job_location_type_joblisting_job_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='joblisting',
            name='benefits',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='joblisting',
            name='company',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='joblisting',
            name='description_json',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='joblisting',
            name='preferred_qualifications',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='joblisting',
            name='required_qualifications',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='joblisting',
            name='responsibilities',
            field=models.TextField(blank=True, null=True),
        ),
    ]
