# Generated by Django 5.1.5 on 2025-03-07 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_joblisting_benefits_joblisting_company_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='joblisting',
            name='description',
        ),
    ]
