# Generated by Django 5.1.5 on 2025-03-07 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_remove_joblisting_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='joblisting',
            name='description_json',
        ),
        migrations.AddField(
            model_name='joblisting',
            name='description',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='joblisting',
            name='benefits',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='joblisting',
            name='preferred_qualifications',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='joblisting',
            name='required_qualifications',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='joblisting',
            name='responsibilities',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
