# Generated by Django 5.1.5 on 2025-03-23 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_enable_pg_trgm'),
    ]

    operations = [
        migrations.AddField(
            model_name='joblisting',
            name='applicants',
            field=models.IntegerField(default=0),
        ),
    ]
