# Generated by Django 5.1.5 on 2025-03-31 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0009_joblisting_experience_level'),
        ('jobs', '0009_joblisting_saved_by'),
    ]

    operations = [
    ]
