# Generated by Django 5.1.5 on 2025-04-03 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0010_savedjob_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='joblisting',
            name='saved_by',
        ),
    ]
