# Generated by Django 5.1.5 on 2025-04-05 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0010_merge_20250331_1103'),
        ('jobs', '0011_remove_joblisting_saved_by'),
    ]

    operations = [
    ]
