# Generated by Django 5.1.5 on 2025-04-13 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0012_merge_20250405_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joblisting',
            name='job_status',
            field=models.CharField(choices=[('open', 'Open'), ('closed', 'Closed'), ('draft', 'Draft')], default='open', max_length=10),
        ),
    ]
